---
title: "First Knit"
author: "Estefania Maldonado"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I went to Antelope Valley College but I graduate from one more high school in Mexico, called Preparatoria Federal por Cooperacion Lic.Gustavo Diaz Ordaz.English is easier for me even though is not my first language, advanced math classes personally are a nightmare. Biomedical sciences are my favorite that's why I earned awards in Chemistry and I was a excellent student in Anatomy, Hematology, Microbiology, Parasitology,etc.   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a MacBook Air.I consider myself a 6 since I know good enough about computer science so I can use it in my daily life but I'm not an expert. Yes, I have a pretty good connection to internet at home.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer people at school call me Estefani since sounds more friendly and usually people call me for my first name using a wrong pronunciation, and "Estefani" for a unknown reason is easier for them.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to become a Dermatologist and improve my human values at the same time, in summary I want to serve my community and support this and next generations contributing with innovations and research. Microbiology is one of the most important subjects for me, since i the foundation of the knowledge in the biomedical fields. My goal is to accomplish a PhD in Dermatology.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
Yes, I was born in Mexico and I moved to United States when I was 18 years old but I would love to visit Switzerland because the nature landscapes and weather. I haven't been in the military but i would choose the air force because I would like to become a pilot, I think is awesome.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
No, I didn't, is my first time taking Math 116 and I haven't taken Math 115. I didn't know that, it's very interesting how the educational system works to help students to have a complete and useful course work indispensable for their careers once their transfer to university. I intend to get a A+ in order to improve my GPA and get into UCLA next year and start majoring in Microbiology and later apply to Medical School.    
   
 






  




